version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    networks:
      private_network:
        ipv4_address: 192.168.1.3
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 3psXscNhooG6MtJmPF7B
    volumes:
      - /path/to/minio/data:/data
    command: server /data --console-address ":9001"

networks:
  private_network:
    external: true

